apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin
commonLabels:
  app: jellyfin

configMapGenerator:
  - name: jellyfin-env
    literals:
      - PUID="1000"
      - PGID="1000"
      - UMASK="002"
      - TZ="Europe/Oslo"

resources:
  - pv-jellyfin-config.yaml
  - pvc-jellyfin-config.yaml
  - pv-jellyfin-media.yaml
  - pvc-jellyfin-media.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
  - http-route.yaml
