apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - ingress-route.yaml
  - auth

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 57.2.1
    releaseName: kube-prometheus-stack
    namespace: monitoring
    valuesInline:
      prometheus-node-exporter:
        hostRootFsMount:
          enabled: false
      prometheusOperator:
        admissionWebhooks:
          failurePolicy: Ignore


