apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: netbird
spec:
  forProvider:
    name: Netbird
    accessType: PUBLIC
    clientId: netbird
    description: Netbird Client
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    oauth2DeviceAuthorizationGrantEnabled: true
    baseUrl: "https://netbird.stonegarden.dev"
    validRedirectUris:
      - "http://localhost:53000"
      - "https://netbird.stonegarden.dev/*"
    validPostLogoutRedirectUris:
      - "https://netbird.stonegarden.dev/*"
    webOrigins:
      - "+"
    realmIdRef:
      name: homelab
---
apiVersion: client.keycloak.crossplane.io/v1alpha1
kind: ProtocolMapper
metadata:
  name: netbird-sub-mapper
spec:
  forProvider:
    name: Username as sub claim
    protocol: openid-connect
    protocolMapper: oidc-usermodel-property-mapper
    config:
      user.attribute: username
      claim.name: sub
      id.token.claim: "true"
      access.token.claim: "true"
      userinfo.token.claim: "true"
    clientIdRef:
      name: netbird
    realmIdRef:
      name: homelab
