apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    dev.stonegarden: home-assistant
spec:
  project: utility
  source:
    repoURL: https://github.com/vehagn/home-assistant
    path: deployment
    targetRevision: HEAD
  destination:
    namespace: home-assistant
    name: in-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

