kind: Deployment
apiVersion: apps/v1
metadata:
  name: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    spec:
      volumes:
        - name: qbittorrent-config
          hostPath:
            path: "/disk/etc/qbittorrent"
        - name: media-data
          hostPath:
            path: "/disk/data"
      containers:
        - name: qbittorrent
          image: cr.hotio.dev/hotio/qbittorrent:legacy
          volumeMounts:
            - mountPath: "/config"
              name: qbittorrent-config
            - mountPath: "/app/data"
              name: media-data
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
            - name: TZ
              value: Europe/Oslo
            - name: WEBUI_PORT
              value: "8080"
          ports:
            - name: web
              containerPort: 8080
            - containerPort: 11010
              protocol: TCP
            - containerPort: 11011
              protocol: TCP
            - containerPort: 11012
              protocol: TCP
            - containerPort: 11013
              protocol: TCP
            - containerPort: 11014
              protocol: TCP
            - containerPort: 11015
              protocol: TCP
            - containerPort: 11010
              protocol: UDP
            - containerPort: 11011
              protocol: UDP
            - containerPort: 11012
              protocol: UDP
            - containerPort: 11013
              protocol: UDP
            - containerPort: 11014
              protocol: UDP
            - containerPort: 11015
              protocol: UDP