apiVersion: v1
kind: ConfigMap
metadata:
  name: regex.list
  namespace: pi-hole
data:
  regex.list: |
    (^|\.)googlevideo\.com$
    (^|\.)twitch\.tv$
    (^|\.)wuaki\.tv$
    (^|\.)youtube\.be$
    (^|\.)youtube\.com$
    (^|\.)xvpn\.com$
    (^|\.)xvpn\.io$
    (^|\.)tiktok\.com$
    (^|\.)musical\.ly$
