apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pi-hole
commonLabels:
  app: pi-hole

resources:
  - namespace.yaml
  - service.yaml
  #- cm-adlists.yaml
  #- cm-ftl.yaml
  #- cm-regex.yaml
  #- cm-whitelist.yaml
  - deployment.yaml
