apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pi-hole
commonLabels:
  app: pi-hole

configMapGenerator:
  - name: pi-hole-env
    envs:
      - config/pi-hole-env
  - name: ftl-conf
    files:
      - config/pihole-FTL.conf
  - name: custom-dnsmasq
    files:
      - config/02-custom.conf
  - name: adlists.list
    files:
      - config/adlists.list
  - name: regex.list
    files:
      - config/regex.list
  - name: whitelist.txt
    files:
      - config/whitelist.txt

resources:
  - namespace.yaml
  - auth-secret.yaml
  - ingress-route.yaml
  - service.yaml
#  - pvc.yaml
  - deployment.yaml

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: application
    releaseName: auth
    valuesFile: auth-values.yaml
