apiVersion: v1
kind: PersistentVolume
metadata:
  name: net-pi-hole-config
  labels:
    app: pi-hole
spec:
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: net-pi-hole-storage
  local:
    path: /disk/etc/net/pi-hole
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gauss