apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-hole-config
  namespace: pi-hole
  labels:
    app: pi-hole
spec:
  storageClassName: net-pi-hole-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
