---
kind: Service
apiVersion: v1
metadata:
  name: pi-hole-udp
  namespace: pi-hole
  annotations:
    metallb.universe.tf/allow-shared-ip: dns
spec:
  selector:
    app: pi-hole
  ports:
    - protocol: UDP
      port: 53
      name: dnsudp
      targetPort: 53
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  name: pi-hole-tcp
  namespace: pi-hole
  annotations:
    metallb.universe.tf/allow-shared-ip: dns
spec:
  selector:
    app: pi-hole
  ports:
    - protocol: TCP
      port: 53
      name: dnstcp
      targetPort: 53
    - protocol: TCP
      port: 80
      name: web
      targetPort: 80
  type: LoadBalancer