apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-pvc
  namespace: plex
spec:
  storageClassName: plex-media-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Ti
