apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: public
  namespace: argocd
  labels:
    dev.stonegarden: application
spec:
  generators:
    - git:
        repoURL: https://github.com/vehagn/homelab
        revision: HEAD
        directories:
          - path: apps/public/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        dev.stonegarden: public
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: public
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/vehagn/homelab
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: '{{ path.basename }}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
