apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: public
  namespace: argocd
spec:
  sourceNamespaces:
    - '*'
  sourceRepos:
    - 'https://github.com/vehagn/*'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'blog'
      server: '*'
    - namespace: 'stonegarden'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'