apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deltahouse
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    dev.stonegarden: delta
spec:
  project: delta
  source:
    repoURL: https://github.com/vehagn/deltahouse-deployment
    path: '.'
    targetRevision: HEAD
  destination:
    namespace: delta
    name: in-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: delta
---
apiVersion: v1
kind: Namespace
metadata:
  name: delta-test
