apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: lgtm
  labels:
    app: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`lgtm.stonegarden.dev`)
      kind: Rule
      services:
        - name: lgtm-grafana
          port: 80
#      middlewares:
#        - name: traefik-forward-auth