apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lgtm

resources:
  - ns.yaml
  - pv.yaml
  - ingress-route.yaml

helmCharts:
  - name: lgtm-distributed
    repo: https://grafana.github.io/helm-charts
    version: 1.0.1
    releaseName: lgtm
    includeCRDs: true
    namespace: lgtm
    valuesFile: values.yaml