grafana:
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      node-exporter-full:
        gnetId: 1860
        revision: 33
        datasource: Mimir
        allowUpdates: true
      postgresql:
        gnetId: 9628
        revision: 7
        datasource: Mimir
        allowUpdates: true
      blackbox:
        gnetId: 14928
        revision: 6
        datasource: Mimir
        allowUpdates: true

mimir:
  alertmanager:
    persistentVolume:
      enabled: false
  ingester:
    persistentVolume:
      enabled: false
  store_gateway:
    persistentVolume:
      enabled: false
  compactor:
    persistentVolume:
      enabled: false
  chunks-cache:
    persistentVolume:
      enabled: false
  minio:
    persistence:
      storageClass: minio
      size: 10Gi
