apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: test-db
  namespace: postgres
  annotations:
    argocd.argoproj.io/tracking-id: test-db:acid.zalan.do/postgresql/postgresql:database/test-db
spec:
  teamId: "acid"
  volume:
    size: 1Gi
    storageClass: db-test-sc
  postgresql:
    version: "15"
  numberOfInstances: 1
  enableMasterLoadBalancer: true
  allowedSourceRanges:
    - 192.168.0.0/16
    - 10.0.0.0/8
  users:
    veh:
      - superuser
      - createdb
    foo_user: [ ]
  #  databases:
  #    test: test
  preparedDatabases:
    bar: { }
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi