apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - http-route.yaml
  - pv-db-test.yaml
  - database.yaml
  #- test-db-svc.yaml

helmCharts:
  - name: postgres-operator
    repo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    #version: 1.15.0-rc.0
    releaseName: "postgres-operator"
    includeCRDs: true
    namespace: postgres
    valuesFile: postgres-operator-values.yaml
  - name: postgres-operator-ui
    repo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
    #version: 1.15.0-rc.0
    releaseName: "postgres-operator-ui"
    #includeCRDs: true
    namespace: postgres
    valuesFile: postgres-operator-ui-values.yaml
