apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: common-env
    namespace: lldap
    literals:
      - TZ="Europe/Oslo"
      - GID="1001"
      - UID="1001"
  - name: lldap-config
    namespace: lldap
    literals:
      - LLDAP_HTTP_URL="https://lldap.stonegarden.dev"
  - name: bootstrap-env
    namespace: lldap
    literals:
      - LLDAP_URL="http://lldap:80"
      - LLDAP_ADMIN_USERNAME="admin"
      - DO_CLEANUP="true"
  - name: users
    namespace: lldap
    files:
      - users/test.json

resources:
  - ns.yaml
  - svc.yaml
  - cnpg-db.yaml
  - lldap-credentials.yaml
  - lldap-config.yaml
  - smtp-credentials.yaml
  - deployment.yaml
  - http-route.yaml
  - bootstrap.yaml
