apiVersion: v1
kind: Service
metadata:
  name: lldap
  namespace: lldap
  annotations:
    io.cilium/lb-ipam-ips: 192.168.1.242
spec:
  type: LoadBalancer
  selector:
    app: lldap
  ports:
    - name: web
      port: 80
      targetPort: web
    - name: ldap
      port: 389
      targetPort: ldap
    - name: ldaps
      port: 636
      targetPort: ldaps
