apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blog
commonLabels:
  app.kubernetes.io/managed-by: argocd

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: application
    releaseName: blog
    valuesFile: values.yaml