apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-apps
  namespace: argocd
  labels:
    dev.stonegarden: infra-apps
spec:
  generators:
    - git:
        repoURL: https://github.com/vehagn/homelab
        revision: HEAD
        directories:
          - path: infra/apps/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        dev.stonegarden: infrastructure
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: infra-apps
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/vehagn/homelab
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true