apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-apps
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/vehagn/homelab'
    - 'oci://registry-1.docker.io/bitnamicharts/keycloak'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'keycloak'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
