apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  namespace: jellyfin
spec:
  storageClassName: jellyfin-config-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
