apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
  namespace: jellyfin
spec:
  storageClassName: jellyfin-media-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Ti
