{{- if include "auth.create" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-forward-auth
  namespace: {{ .Values.namespace }}
  labels:
    app: traefik-forward-auth
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    {{- include "common.annotations" . | nindent 4 }}
data:
  traefik-forward-auth.ini: |-
    cookie-name = {{ .Values.auth.cookieName | default (print "_" .Values.namespace "_auth") | quote }}
    cookie-domain = {{ .Values.auth.cookieDomain | quote }}
    auth-host = {{ include "auth.host" . | quote }}
    log-level = {{ .Values.auth.logLevel | quote }}
    {{- range .Values.auth.domains }}
    domain = {{ . | quote }}
    {{- end }}
    {{- range .Values.auth.whitelist }}
    whitelist = {{ . | quote }}
    {{- end }}
    {{- range $key, $val := .Values.auth.extraConfig -}}
    {{ $key | nindent 4 }} = {{ $val | quote }}
    {{- end }}
{{- end }}