apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-arr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`torrent.stonegarden.dev`)
      kind: Rule
      services:
        - name: qbittorrent
          port: 8112
      middlewares:
        - name: traefik-forward-auth
  tls:
    certResolver: letsencrypt