apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cm-common-env.yaml
  - ingress.yaml
  - auth.yaml
  - torrent
  - prowlarr.yaml
  - sonarr.yaml
  - radarr.yaml
  - lidarr.yaml