apiVersion: apps/v1
kind: Deployment
metadata:
  name: signal
  namespace: netbird
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: signal
  template:
    metadata:
      labels:
        app.kubernetes.io/name: signal
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: abel
      containers:
      - name: signal
        image: docker.io/netbirdio/signal:0.35.2 # renovate: docker=docker.io/netbirdio/signal
        args: [--port, $(PORT), --log-level, $(LOG_LEVEL), --log-file, console]
        envFrom:
          - configMapRef:
              name: signal-config
        volumeMounts:
          - name: signal
            mountPath: /var/lib/netbird
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          tcpSocket:
            port: http
        readinessProbe:
          tcpSocket:
            port: http
        resources:
          requests:
            memory: 16Mi
            cpu: 10m
          limits:
            memory: 64Mi
            cpu: 2000m
      volumes:
        - name: signal
          persistentVolumeClaim:
            claimName: signal
