apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: signal-config
    namespace: netbird
    literals:
      - LOG_LEVEL="info"
      - PORT="80"

resources:
  - deployment.yaml
  - pvc.yaml
  - svc.yaml
