apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: stonegarden
  namespace: gateway
  annotations:
    cert-manager.io/issuer: cloudflare-issuer
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      io.cilium/lb-ipam-ips: 192.168.1.172
  listeners:
    - protocol: HTTPS
      port: 443
      name: https-blog
      hostname: blog.stonegarden.dev
      tls:
        certificateRefs:
          - kind: Secret
            name: cloudflare-cert
      allowedRoutes:
        namespaces:
          from: All
    - protocol: HTTPS
      port: 443
      name: https-remark42
      hostname: remark42.stonegarden.dev
      tls:
        certificateRefs:
          - kind: Secret
            name: cloudflare-cert
      allowedRoutes:
        namespaces:
          from: All
    - protocol: HTTPS
      port: 443
      name: https-haos
      hostname: haos.stonegarden.dev
      tls:
        certificateRefs:
          - kind: Secret
            name: cloudflare-cert
      allowedRoutes:
        namespaces:
          from: All
    - protocol: HTTPS
      port: 443
      name: https-jellyfin
      hostname: jellyfin.stonegarden.dev
      tls:
        certificateRefs:
          - kind: Secret
            name: cloudflare-cert
      allowedRoutes:
        namespaces:
          from: All
    - protocol: HTTPS
      port: 443
      name: https-postgres
      hostname: postgres.stonegarden.dev
      tls:
        certificateRefs:
          - kind: Secret
            name: cloudflare-cert
      allowedRoutes:
        namespaces:
          from: All
    - protocol: HTTPS
      port: 443
      name: https-gateway
      hostname: gateway.stonegarden.dev
      tls:
        certificateRefs:
          - kind: Secret
            name: cloudflare-cert
      allowedRoutes:
        namespaces:
          from: All
    - protocol: HTTPS
      port: 443
      name: https-domain-gateway
      hostname: stonegarden.dev
      tls:
        certificateRefs:
          - kind: Secret
            name: cloudflare-cert
      allowedRoutes:
        namespaces:
          from: All
#    - protocol: HTTPS
#      port: 443
#      name: https-wildcard
#      hostname: "*.stonegarden.dev"
#      tls:
#        certificateRefs:
#          - kind: Secret
#            name: cloudflare-cert
#      allowedRoutes:
#        namespaces:
#          from: All
