apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    plugin:
      name: kustomize-build-with-helm
    path: infra/monitoring
    repoURL: https://github.com/vehagn/homelab
    targetRevision: HEAD
  destination:
    namespace: monitoring
    name: in-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
