apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
  namespace: plex
spec:
  storageClassName: plex-config-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
