apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pv.yaml
  - ns.yaml
  - http-route.yaml
  - secret-keycloak-postgresql.yaml
  - secret-keycloak-admin.yaml

helmCharts:
  - name: keycloak
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 21.1.1
    releaseName: keycloak
    includeCRDs: true
    namespace: keycloak
    valuesFile: values.yaml


