# https://github.com/bitnami/charts/blob/main/bitnami/keycloak/values.yaml
auth:
  adminUser: admin
  existingSecret: keycloak-admin
  passwordSecretKey: password

#production: true

proxy: edge

ingress:
  enabled: true
  hostname: keycloak.stonegarden.dev
  path: /
  tls: true

postgresql:
  enabled: true
  auth:
    existingSecret: keycloak-postgresql
  # https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
  primary:
    persistence:
      enabled: true
      volumeName: keycloak-db