apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay
  namespace: netbird
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: relay
  template:
    metadata:
      labels:
        app.kubernetes.io/name: relay
    spec:
      containers:
        - image: netbirdio/relay:0.35.2 # renovate: docker=netbirdio/relay
          imagePullPolicy: IfNotPresent
          name: netbird-relay
          envFrom:
            - configMapRef:
                name: relay-config
            - secretRef:
                name: relay-secret
          ports:
            - containerPort: 80
              name: relay
              protocol: TCP
