apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: netbird-relay
  name: netbird-relay
  namespace: netbird
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: netbird-relay
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: netbird-relay
        app.kubernetes.io/name: netbird-relay
    spec:
      containers:
        - image: netbirdio/relay:0.35.2 # renovate: docker=netbirdio/relay
          imagePullPolicy: IfNotPresent
          name: netbird-relay
          envFrom:
            - configMapRef:
                name: relay-config
          env:
            - name: NB_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  key: authSecret
                  name: netbird-relay-credentials
          ports:
            - containerPort: 80
              name: relay
              protocol: TCP
