apiVersion: v1
kind: Service
metadata:
  name: netbird-relay
  namespace: netbird
  labels:
    app.kubernetes.io/name: netbird-relay
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: netbird-relay
  ports:
  - name: relay
    port: 80
    protocol: TCP
    targetPort: 80
