apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: agent-setup-key
  namespace: netbird
spec:
  encryptedData:
    NB_SETUP_KEY: AgCf/R+4ARcoG/r0tApenFw4cIaLdHPJcSB2vbK/3Hll1AGTqHEyZvfWAU2HIeTr8MGGZpB5Fg9TyDcJ3rM340QspgmK4nf8mppQoJo/GP5fM/QWvXyRyb1RPgS+5U3faiawStDWYsf2tugB+OLxPx4V4ZYtldF8dMgsUFk5o3Spja6+jhC19ZCq136RrgO5oS7Tgns20XuyYqc/LwapjNdmBHUiEXajnz1egTL71GFRrhspWPTaOhpHPoV9ZU1rpi1ZtY12sazrjsu3WvnBHzqrsutZm7aX9vUDA3r5zB2E6c5Q2gI4nEACT6Kbvl8FjSgAYkkSWXcjsbNSZ8YfWolSrVPGGc5f6eMdk52b32ednyfXEdi+kx+JOmLguXJiPljEqmJ3EcHmvHDsoQN1cY9+FkGCgVHXgXAgRxnhJ/kOHyK/JGYrAz2g64owfYKr1W+BB9BVIvqY4nVZ9sj71AymQx1ABxxAg/oNDUuI4k2PfoVUd2j9EK6drVpDscPz9z/pCreCvSwACPznSbMAgkeCdwSxf/kaSzCxxscv/j1mP+mCp8i8vmXZkaVxQEWCh1jZVzP6VL9RDSxhGAV3Neq9FJy8x3Gegn8A1mhjoOkYQHPtgpZHvwtMdPTM3lpyPuoBXdT/sHtHnHLtq5383K0O3J57DgjGM0vp5TzszE0E5XqV+ynxq6bghKWUA209I8Q1WO+Q785xrHg5+aExjxKE50vIhjyjfm+1fKa7YZ6pqMEuzvw=
  template:
    metadata:
      name: agent-setup-key
      namespace: netbird
    type: Opaque
