apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agent
  namespace: netbird
spec:
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: agent
          image: docker.io/netbirdio/netbird:0.35.2 # renovate: docker=docker.io/netbirdio/netbird
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              add: [ NET_ADMIN, PERFMON, BPF ]
          envFrom:
            - configMapRef:
                name: agent-config
          env:
            - name: NB_SETUP_KEY
              valueFrom:
                secretKeyRef:
                  name: agent-setup-key
                  key: setupKey
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          emptyDir: { }
