apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-time-slicing
  namespace: nvidia-device-plugin
data:
  time-slicing: |-
    version: v1
    sharing:
      timeSlicing:
        failRequestsGreaterThanOne: true
        resources:
          - name: nvidia.com/gpu
            replicas: 10
