apiVersion: v1
kind: ConfigMap
metadata:
  name: time-slicing
data:
  default: |-
    version: v1
    sharing:
      timeSlicing:
        resources:
          - name: nvidia.com/gpu
            replicas: 10
