apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgres
  namespace: keycloak
spec:
  storageClassName: proxmox-csi
  volumeName: pv-keycloak-postgres
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
