apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbird-credentials
  namespace: coturn
spec:
  encryptedData:
    NETBIRD_PASSWORD: AgCSANuCiynyFeiRsWbHflay74tMsZ7lUiTRo0j7rcZmloSvvzQPYR+jdcubdagXaoskGHr50AplXE+2nv1VZ4GJl3Ik66YgwRkI2qdQtyIpKFq2650sVHQSSE7CqPnkIRD5/1UllSlVuBdb9E3bMbVB7nI6jqxxNRokfVN3yvVC3I0Xxqlb7FnYxwqqp1LsOkEdb0wWNNdAWS5V88px5U5d7azMhwexJuF+DBhRP+A5wqxaMvcoqPOBd22AsLiHC/pxThIq6yf/vUQSd1oBEcBhOqQVKsLWdRHBclKeoEjrx9sflaF7QAFlTiqHU3SqrnSU9owTyVxoytHCXQu3UwWEfn3AvseQ/uyDvxPBCYIILAv3CfuIwzbBpj7IR6OBWuJRRLVa4EUKo30tzglo34ZQc9/499KUqjgqNFw5NUrOmcpl+V7Q4O0xju/GGU8ykkHukR7KCT22yqhzbTNNepwnyvKPx4OEHUBiujf03fqJphSTdwvkfLDJgFW+Zfq7xsk3KVYBxU+ENA4425qKFgPWheIE13Gca5OOWD8KTc4rquBG0eL4B4CYUBb9Yyo3t8SePlrtjbQzoC6UU9YihXCMlWcYfnVzJfpWxPNsRll/2aptwz0THRLNNk4RdOJtGcQIcmFplEsvgP4v8f2pt0lDM6SfwwmqUAR/RYnNwa1IzuvjiUSyfMABuTUe3lB9zO/97HsHgt19DqlUOQMxFbVXSlo9mxMJ5nycJvVn+0HP4xx/srCxRgxo
    NETBIRD_USER: AgCCz+ai0Oj2UjXQjwhoLX3Sr4QNig5vqiBmnN+S9dFU7tgVWX55T6WgWQA7Z2UfOpRI5sbJYJCEdXhhsBinfIhosg5JWPAlcxnW1qUEdFU1j2F1COSjRzZyJShCvW/h9jiGoUu94DYLNAE146qqQrjkYB5JMZEtaB2qJJBaeZNYTIzKQbrmZuc8YNJIIt6trfDAG48zDBWobLF0InW+xNsdGDgTIJIyer0ecgIsqMy1sGVGORLT/vIsDpQZYwcdaYm67t8C49qUhlsq7qBY1pMxGi98Wm92n7xgAfeu1k0nDq3LQ1rxVRBY2TrwKYcmrsmKzxPpCw8/KO/hVVcLOIELyUDtE5zHohSZs/Qq/C7xIPOMK9zjj+7wDkZpJPesinWCHZAk7qjXBMKwKTz9YXBcDOQ36OQU21GQC9jxFTHcd5vzlTplZ7Wa5qT9swKZuyvQR6Bis1jZsRKqt4F/IfxdZii5rCCb9YL42YDYpDtC/Ar5kw0CARryVTpIFhyU0Sn+7i82P2uG86QZC/0X+Is3CPdL4sqHj1JEkxWlPQhh+4FH8MhdPJjvHRwUQ7dVjIrQsmUbajM5Dmqpr7k7lkxUAzzkH9VDSFmzkRc4lltpV7npIopZNLoKXoY2QK3EnHXWtkNWYL6JMRbB/TsmQ89s1DB13cgVRA69gUX1LDMbdufzWypAevCY2GkP+U2u5Z2b86rV1LiC
  template:
    metadata:
      name: netbird-credentials
      namespace: coturn
    type: Opaque
