apiVersion: v1
kind: Service
metadata:
  name: coturn
  namespace: coturn
  annotations:
    io.cilium/lb-ipam-ips: 192.168.1.226
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: coturn
  ports:
    - name: tcp
      port: 3478
      protocol: TCP
      targetPort: tcp
    - name: udp
      port: 3478
      protocol: UDP
      targetPort: udp
    - name: tcp-tls
      port: 5349
      protocol: TCP
      targetPort: tcp-tls
    - name: udp-tls
      port: 5349
      protocol: UDP
      targetPort: udp-tls
