namespace: arr
env:
  - name: PUID
    valueFrom:
      configMapKeyRef:
        name: common-env
        key: PUID
  - name: PGID
    valueFrom:
      configMapKeyRef:
        name: common-env
        key: PGID
  - name: UMASK
    valueFrom:
      configMapKeyRef:
        name: common-env
        key: UMASK
  - name: TZ
    valueFrom:
      configMapKeyRef:
        name: common-env
        key: TZ
additionalVolumes:
  - name: data
    mountPath: /app/data
    value:
      hostPath:
        path: /disk/data
additionalLabels:
  app.kubernetes.io/part-of: arr
auth:
  enabled: true
  create: false
