kind: Deployment
apiVersion: apps/v1
metadata:
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    spec:
      volumes:
        - name: radarr-config
          hostPath:
            path: "/disk/etc/radarr"
        - name: media-data
          hostPath:
            path: "/disk/data"
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/config"
              name: radarr-config
            - mountPath: "/app/data"
              name: media-data
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Oslo
          ports:
            - name: web
              containerPort: 7878