apiVersion: v1
kind: PersistentVolume
metadata:
  name: remark42
  labels:
    app: remark42
spec:
  capacity:
    storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: remark42-storage
  local:
    path: /disk/etc/blog/remark42
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gauss
