apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: remark42-http-route
spec:
  parentRefs:
    - name: stonegarden
      namespace: gateway
  hostnames:
    - "remark42.stonegarden.dev"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: remark42-web
          port: 80