apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/managed-by: argocd

configMapGenerator:
  - name: remark42-env
    envs:
      - config/env-remark42

resources:
  - deployment.yaml
  - http-route.yaml
  - pv.yaml
  - pvc.yaml
  - secret-github.yaml
  - secret-google.yaml
  - secret-remark42.yaml
  - service.yaml
  - ingress-route.yaml