apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: remark42
  namespace: blog
  labels:
    app: remark42
spec:
  storageClassName: remark42-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
