{{- if include "auth.create" . }}
apiVersion: v1
kind: Service
metadata:
  name: traefik-forward-auth
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    {{- include "common.annotations" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: traefik-forward-auth
  ports:
    - name: auth
      port: {{ .Values.auth.port }}
      targetPort: auth
  {{- end }}