apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#  - https://raw.githubusercontent.com/sergelogvinov/proxmox-csi-plugin/v0.7.0/docs/deploy/proxmox-csi-plugin-release.yml
  - storage-class.yaml

#images:
#  - name: ghcr.io/sergelogvinov/proxmox-csi-node
#    newTag: edge
#  - name: ghcr.io/sergelogvinov/proxmox-csi-controller
#    newTag: edge

helmCharts:
  - name: proxmox-csi-plugin
    repo: oci://ghcr.io/sergelogvinov/charts/proxmox-csi-plugin
    version: 0.7.0
    releaseName: proxmox-csi-plugin
    includeCRDs: true
    namespace: csi-proxmox
