apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ip-pool.yaml
  - announce.yaml
  - pv-cilium-spire-config.yaml

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io
    version: 1.15.3
    releaseName: "cilium"
    includeCRDs: true
    namespace: kube-system
    valuesFile: values.yaml