cluster:
  name: gauss
  id: 0

#debug:
#  enabled: true

k8sServiceHost: "192.168.1.12"
k8sServicePort: "6443"

# Roll out cilium agent pods automatically when ConfigMap is updated.
rollOutCiliumPods: true

# Increase rate limit when doing L2 announcements
k8sClientRateLimit:
  qps: 50
  burst: 100

kubeProxyReplacement: true

l2announcements:
  enabled: true

externalIPs:
  enabled: true

enableCiliumEndpointSlice: true

operator:
  # Can't have more replicas than nodes
  replicas: 1

hubble:
  enabled: true
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true
    frontend:
      server:
        ipv6:
          enabled: false
  tls:
    auto:
      enabled: true
      method: helm
      certValidityDuration: 1095

# mTLS
authentication:
  enabled: true
  mutual:
    spire:
      enabled: true
      install:
        server:
          dataStorage:
            storageClass: cilium-spire-sc
