cluster:
  name: gauss
  id: 0

k8sServiceHost: "192.168.1.12"
k8sServicePort: "6443"

kubeProxyReplacement: true

operator:
  # Can't have more replicas than nodes
  replicas: 1
  rollOutPods: true

# Roll out cilium agent pods automatically when ConfigMap is updated.
rollOutCiliumPods: true

#debug:
#  enabled: true

image:
  tag: "v1.15.0-rc.0"

# Increase rate limit when doing L2 announcements
k8sClientRateLimit:
  qps: 100
  burst: 200

l2announcements:
  enabled: true

externalIPs:
  enabled: true

enableCiliumEndpointSlice: true

gatewayAPI:
  enabled: true

hubble:
  enabled: true
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true

# mTLS
authentication:
  enabled: false
  mutual:
    spire:
      enabled: false
      install:
        server:
          dataStorage:
            storageClass: cilium-spire-sc
