cluster:
  id: 0
  name: kubernetes

encryption:
  nodeEncryption: false

k8sServiceHost: 192.168.1.12
k8sServicePort: 6443

kubeProxyReplacement: strict

operator:
  replicas: 1

serviceAccounts:
  cilium:
    name: cilium
  operator:
    name: cilium-operator

tunnel: vxlan