apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

helmGlobals:
  chartHome: ../../../charts

helmCharts:
  - name: application
    releaseName: auth
    valuesFile: auth-values.yaml

resources:
  - traefik-forward-auth-secrets.yaml
