apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrent-config
  namespace: torrent
spec:
  storageClassName: proxmox-csi
  volumeName: pv-torrent
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
