apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: common-env
    namespace: arr
    literals:
      - TZ="Europe/Oslo"

resources:
  - sonarr/pvc.yaml
  - sonarr/deployment.yaml
