apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth-secret.yaml

helmGlobals:
  chartHome: ../../../charts

helmCharts:
  - name: application
    releaseName: auth
    valuesFile: auth-values.yaml
