apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: management-config-template
    namespace: netbird
    files:
      # https://github.com/netbirdio/netbird/blob/main/infrastructure_files/management.json.tmpl
      - config/management.json.tmpl
  - name: management-auth-config
    namespace: netbird
    literals:
      - AUTH_AUTHORITY="https://authelia.stonegarden.dev"
#      - AUTH_OIDC_CONFIGURATION_ENDPOINT="https://authelia.stonegarden.dev/.well-known/openid-configuration"
#      - AUTH_DEVICE_AUTH_AUTHORITY="https://authelia.stonegarden.dev"
#      - AUTH_DEVICE_AUTH_PROVIDER="hosted"
#      - AUTH_DEVICE_AUTH_CLIENT_ID="netbird"
#      - AUTH_DEVICE_AUTH_AUDIENCE="netbird"
#      - AUTH_DEVICE_AUTH_DEVICE_AUTHORIZATION_ENDPOINT="https://authelia.stonegarden.dev/protocol/openid-connect/auth"
#      - AUTH_DEVICE_AUTH_TOKEN_ENDPOINT="https://authelia.stonegarden.dev/protocol/openid-connect/token"
#      - AUTH_DEVICE_AUTH_SCOPE="openid"
#      - AUTH_DEVICE_AUTH_USE_ID_TOKEN="false"
      - AUTH_CLIENT_ID="netbird"
      - AUTH_AUDIENCE="netbird"
#      - AUTH_PKCE_REDIRECT_URLS='[ "http://localhost:53000" ]'
#      - AUTH_PKCE_USE_ID_TOKEN=true
      - AUTH_SUPPORTED_SCOPES="openid profile email offline_access netbird-api"
  - name: management-connection-config
    namespace: netbird
    literals:
      - RELAY_URI="rels://netbird.stonegarden.dev:443"
      - SIGNAL_URI="netbird.stonegarden.dev:443"
      - SIGNAL_PROTOCOL="https"
      - STUN_URI="stun:coturn.stonegarden.dev:5349"
      - TURN_URI="turn:coturn.stonegarden.dev:5349"
  - name: management-runtime-config
    namespace: netbird
    literals:
      - LOG_LEVEL="info"
      - DNS_DOMAIN="stonegarden.dev"
  - name: management-oidc-key-check-config
    namespace: netbird
    literals:
      - KEY_CHECK_INTERVAL_SECONDS="900"

resources:
  - deployment.yaml
  - svc.yaml
  - pvc.yaml
  - coturn-credentials.yaml
