kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: management
  namespace: netbird
spec:
  storageClassName: proxmox-csi
  volumeName: pv-netbird-management
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512M
