apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: cloudflared-local-config
    namespace: cloudflared
    files:
      - config/local.yaml

resources:
  - ns.yaml
  - local.yaml
  - local-token.yaml
  - remote.yaml
  - remote-token.yaml
