apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: net-aux
  name: net-aux
  namespace: net-aux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-aux
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: net-aux
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 127.0.0.1
      containers:
        - name: pi-hole
          image: pihole/pihole:2023.05.2
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: pi-hole-env
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dchp
              containerPort: 67
              protocol: UDP
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          resources:
            requests:
              cpu: "20m"
              memory: "512Mi"
            limits:
              cpu: "250m"
              memory: "896Mi"
          livenessProbe:
            tcpSocket:
              port: dns-tcp
            initialDelaySeconds: 60
            failureThreshold: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - 'dig'
                - '@127.0.0.1'
                - 'github.com'
            initialDelaySeconds: 60
            failureThreshold: 3
            timeoutSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /etc/pihole
            - name: custom-dnsmasq
              mountPath: /etc/dnsmasq.d/02-custom.conf
              subPath: 02-custom.conf
            #- name: ftl-conf
            #  mountPath: /etc/pihole/pihole-FTL.conf
            #  subPath: pihole-FTL.conf
            - name: ad-lists
              mountPath: /etc/pihole/adlists.list
              subPath: adlists.list
            - name: regex
              mountPath: /etc/pihole/regex.list
              subPath: regex.list
            - name: whitelist
              mountPath: /etc/pihole/whitelist.txt
              subPath: whitelist.txt
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  key: tunnel-token
                  name: tunnel-token
          volumeMounts:
            - name: cloudflared-config
              mountPath: /etc/cloudflared/config/config.yaml
              subPath: config.yaml
      restartPolicy: Always
      volumes:
        - name: config
          emptyDir: {}
        #  persistentVolumeClaim:
        #    claimName: pi-hole-config
        - name: custom-dnsmasq
          configMap:
            name: custom-dnsmasq
        #- name: ftl-conf
        #  configMap:
        #    name: ftl-conf
        - name: ad-lists
          configMap:
            name: adlists.list
        - name: regex
          configMap:
            name: regex.list
        - name: whitelist
          configMap:
            name: whitelist.txt
        - name: cloudflared-config
          configMap:
            name: cloudflared-config
        - name: tunnel-token
          secret:
            secretName: tunnel-token
