kind: Deployment
apiVersion: apps/v1
metadata:
  name: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    spec:
      volumes:
        - name: sonarr-config
          hostPath:
            path: "/disk/etc/sonarr"
        - name: media-data
          hostPath:
            path: "/disk/data"
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/config"
              name: sonarr-config
            - mountPath: "/app/data"
              name: media-data
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Oslo
          ports:
            - name: web
              containerPort: 8989