apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-arr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`hass.stonegarden.dev`)
      kind: Rule
      services:
        - name: home-assistant
          port: 8123
  tls:
    certResolver: letsencrypt