kind: Deployment
apiVersion: apps/v1
metadata:
  name: lidarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    spec:
      volumes:
        - name: lidarr-config
          hostPath:
            path: "/disk/etc/lidarr"
        - name: media-data
          hostPath:
            path: "/disk/data"
      containers:
        - name: lidarr
          image: lscr.io/linuxserver/lidarr
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/config"
              name: lidarr-config
            - mountPath: "/app/data"
              name: media-data
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Oslo
          ports:
            - name: web
              containerPort: 8686