kind: Deployment
apiVersion: apps/v1
metadata:
  name: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    spec:
      volumes:
        - name: prowlarr-config
          hostPath:
            path: "/mnt/sdb1/homelab/config/prowlarr"
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:develop
          volumeMounts:
            - mountPath: "/config"
              name: prowlarr-config
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Oslo
          ports:
            - name: web
              containerPort: 9696