apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications
  source:
    path: helm/application
    repoURL: https://github.com/vehagn/homelab
    targetRevision: HEAD
    helm:
      values: |
        name: test2
        namespace: test
        image: 
          name: containous/whoami
        service:
          containerPort: 80
        auth:
          enabled: true
          create: false
  destination:
    namespace: test
    name: in-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
