apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloudflare-issuer
  namespace: traefik-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: veghag@gmail.com
    privateKeySecretRef:
      name: cloudflare-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-token-cert-manager
              key: api-token