deployment:
  dnsConfig:
    nameservers:
      - 192.168.1.153
      - 192.168.1.154

service:
  annotations:
    io.cilium/lb-ipam-ips: 192.168.1.142

ingressRoute:
  dashboard:
    entryPoints:
      - websecure
    matchRule: Host(`traefik.stonegarden.dev`)
    middlewares:
      - name: traefik-forward-auth

tlsStore:
  default:
    defaultCertificate:
      secretName: wildcard-stonegarden-dev-tls