apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: plex

configMapGenerator:
  - name: plex-env
    namespace: plex
    literals:
      - TZ="Europe/Oslo"

resources:
  - ns.yaml
  - svc.yaml
  - pvc.yaml
  - ingress.yaml
  - deployment.yaml
