apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: remote
  namespace: cloudflared
spec:
  selector:
    matchLabels:
      app: remote
  template:
    metadata:
      labels:
        app: remote
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2024.4.1
          imagePullPolicy: IfNotPresent
          args: [ tunnel, --no-autoupdate, run ]
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            initialDelaySeconds: 10
            failureThreshold: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 20m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  key: tunnel-token
                  name: remote-token
