apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    tunnel-token: AgCD0EVPfDDgsUEm4GyjGbC1WtpwPHHZpMF2KuonW5fXWWQMM4ju/0sZT7hMdi4SP8oGjRKQ/l844i3F/dlWzOoKZHXxH8QjMoHUjFWzPW50Kk+U7bplwNAZylvz2Ng9jCujgQUEXSeOTwM9Zc5ssBzS0DpiNkXxy4aNroCFScW6w8WcGCxGyHUXB4iy0QP6XGDLbElJryhqqOrPoS9BlTvycSKShYGD+9dNyw4ZyLvfGX14ijZgRWR6imCUwirm8teMMu2hlyNVfhO/quBtfA86GQGYivTrofR+yTN++4t5FBmJ87HqkkW/E1gGG5x8G1EI5VYggs2jTXXPgH3ckw+fKA7vgTHTzbEVjPKW1Tn+W85CWOqfLnQbxvqqhahNwZ96GX2KAgfNbqdLpeBJvvG6Li7esluxkOW6hrWLlaoPtz4E4de2LtKv4tsXkZhqtpAIPRca/cZVNxiYD2+NPx7dliKbV07CUhqn5v9G9+nq7N4nena+KFJDOwgRwDk4KVnBL/ssk+45oUY70UZ7Y/iSKj25BMVPLO3eMVUxAlY27Ec0MNL0TXfy1mm3X2vyyA3mnhDnZrXMbPWeNPijsID2fzH7vZeRuEef6O7kNzvWqgZGNbeOgtQY0T2b3iTdSOdCz/q+Sj4OXZBXyjKcNLQH5iV2nOVdc+JAiX0IWc16taOPfk7JvNMoHzk5puRPacQEn91ZAwSngb8f0PkLfHqy0hWeb06OzuLvy+VE0M75vUINuSAGa3l1iXvI8oD2UNq1THFyW+JDYi+sxhaLuoCLhKBKt2CKsQ2hfCVKzyjInD7BcTIQjHKJRJu1tOp5qiAcWDr7ojP06Y4qMHCF7a/9Qdzv8EtN5nKRL4PmSmyeTuD5L8gl7PnROXG8e6gny5oJL/QeOwqk/mHpIJIxib+ZQAJM0LYMFGR/hw7Tpxhgen4ahKKVm60f
  template:
    metadata:
      name: tunnel-token
      namespace: cloudflared