apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: common-env
    namespace: audiobookshelf
    literals:
      - TZ=Europe/Oslo

resources:
  - ns.yaml
  - pvc.yaml
  - svc.yaml
  - http-route.yaml
  - deployment.yaml
