apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  storageClassName: proxmox-csi
  volumeName: pv-audiobookshelf
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4G
