apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    path: infra
    repoURL: https://github.com/vehagn/homelab
    targetRevision: HEAD
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      selfHeal: true