apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.8.2/manifests/install.yaml
  - ingress.yaml
  - cm-argocd-plugin.yaml

patchesStrategicMerge:
  # Plugin to enable Kustomize with Helm
  - patches/argocd-repo-server-plugin-sidecar.yaml
  # Ignore CiliumIdentity CRDs
  - patches/argocd-cm-resource-exclusion-cilium-identity-patch.yaml
  # Let Traefik manage TLS-termination
  - patches/argocd-cmd-params-cm-server-insecure-patch.yaml

