apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: application
    releaseName: auth
    valuesFile: auth-values.yaml

resources:
  - namespace.yaml
  - traefik-forward-auth-secrets.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.0/manifests/install.yaml
  - ingress.yaml
  - argocd-cm-cmp-kustomize-build-with-helm.yaml

patches:
  # Copy binaries from ArgoCD-image
  - path: patches/argocd-repo-copyutil-patch.yaml
  # Plugin to enable Kustomize with Helm
  - path: patches/argocd-repo-server-plugin-sidecar-patch.yaml
#  # Ignore CiliumIdentity CRDs
#  - path: patches/argocd-cm-resource-exclusion-cilium-identity-patch.yaml
  # Configure tracking method to annotation
  # https://argo-cd.readthedocs.io/en/stable/user-guide/resource_tracking/#additional-tracking-methods-via-an-annotation
  - path: patches/argocd-cm-tracking-method-annotation.yaml
  # Traefik handles TLS
  - path: patches/argocd-cmd-params-cm-server-insecure-patch.yaml
