apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - ingress.yaml
  - project.yaml
  - infrastructure.yaml
  - applications.yaml

patchesStrategicMerge:
  # Kustomize --enable-helm plugin for Helm charts
  - patches/argocd-cm-kustomize-helm-patch.yaml
  # Ignore CiliumIdentity CRDs
  - patches/argocd-cm-resource-exclusion-cilium-identity-patch.yaml
  # Let Traefik manage TLS-termination
  - patches/argocd-cmd-params-cm-server-insecrure-patch.yaml

