apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/vehagn/*'
  destinations:
    - namespace: 'argocd'
      server: '*'