apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  labels:
    dev.stonegarden: vpn
    app.kubernetes.io/managed-by: argocd

resources:
  - project.yaml
  - application-set.yaml
